#!/usr/bin/env bash
# export-abis.sh — Sync forge build ABI artifacts to frontend TypeScript constants
#
# Usage:
#   bash export-abis.sh [project-root]
#
# Reads:  packages/contracts/out/**/<Contract>.json  (forge build artifacts)
# Writes: apps/web/src/abis/<Contract>.ts            (TypeScript `as const` exports)
#
# Requirements: jq, bash >= 4
# Exit codes:
#   0 — all ABIs exported successfully
#   1 — no artifacts found, jq missing, or path validation failed

set -euo pipefail

PROJECT_ROOT="${1:-$(pwd)}"

if [[ ! -d "$PROJECT_ROOT" ]]; then
  echo "ERROR: project root '${PROJECT_ROOT}' is not a directory." >&2
  exit 1
fi

# Validate required directories exist
CONTRACTS_OUT="${PROJECT_ROOT}/packages/contracts/out"
ABI_DEST="${PROJECT_ROOT}/apps/web/src/abis"

if [[ ! -d "$CONTRACTS_OUT" ]]; then
  echo "ERROR: forge build output not found at '${CONTRACTS_OUT}'." >&2
  echo "       Run 'forge build' from packages/contracts first." >&2
  exit 1
fi

# Require jq
if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required but not installed." >&2
  echo "       Install: brew install jq  OR  apt-get install jq" >&2
  exit 1
fi

# Create output directory
mkdir -p "$ABI_DEST"

EXPORTED=0
SKIPPED=0

# Convert PascalCase contract name to SCREAMING_SNAKE_CASE constant name
# e.g., MyToken -> MY_TOKEN, ERC20Token -> ERC20_TOKEN
to_screaming_snake() {
  local name="$1"
  echo "$name" \
    | sed 's/\([A-Z][A-Z]*\)\([A-Z][a-z]\)/\1_\2/g' \
    | sed 's/\([a-z0-9]\)\([A-Z]\)/\1_\2/g' \
    | tr '[:lower:]' '[:upper:]'
}

echo ""
echo "══════════════════════════════════════════════"
echo "  EVM dApp ABI Export Pipeline"
echo "  Source : ${CONTRACTS_OUT}"
echo "  Dest   : ${ABI_DEST}"
echo "══════════════════════════════════════════════"
echo ""

# Iterate over all forge build artifacts
# Pattern: out/<ContractName>.sol/<ContractName>.json
while IFS= read -r -d '' artifact; do
  # artifact path: .../<ContractName>.sol/<ContractName>.json
  artifact_basename=$(basename "$artifact" .json)
  parent_dir=$(basename "$(dirname "$artifact")" .sol)

  # Skip if basename doesn't match parent (happens with dependency artifacts)
  if [[ "$artifact_basename" != "$parent_dir" ]]; then
    (( SKIPPED++ )) || true
    continue
  fi

  contract_name="$artifact_basename"

  # Skip test and script contracts (end in .t or .s by convention)
  # Also skip forge-std internals
  if [[ "$contract_name" == *Test* ]] || \
     [[ "$contract_name" == *Script* ]] || \
     [[ "$contract_name" == "Vm" ]] || \
     [[ "$contract_name" == "StdAssertions" ]] || \
     [[ "$contract_name" == "StdChains" ]] || \
     [[ "$contract_name" == "StdCheats" ]]; then
    (( SKIPPED++ )) || true
    continue
  fi

  # Check ABI is non-empty array
  abi_length=$(jq '.abi | length' "$artifact" 2>/dev/null || echo "0")
  if [[ "$abi_length" -eq 0 ]]; then
    echo "  ⊘  ${contract_name} — empty ABI, skipping"
    (( SKIPPED++ )) || true
    continue
  fi

  # Build constant name
  const_name=$(to_screaming_snake "$contract_name")_ABI

  # Destination file path (reject any path outside ABI_DEST)
  dest_file="${ABI_DEST}/${contract_name}.ts"
  if [[ "$dest_file" != "${ABI_DEST}/"* ]]; then
    echo "  ✗  ${contract_name} — path traversal detected, skipping" >&2
    continue
  fi

  # Extract ABI and write TypeScript constant
  abi_json=$(jq -r '.abi' "$artifact")

  cat > "$dest_file" << TSEOF
// Auto-generated by export-abis.sh from forge build artifacts.
// Do not edit this file manually — re-run export-abis.sh after forge build.
export const ${const_name} = ${abi_json} as const
TSEOF

  echo "  ✓  ${contract_name} → abis/${contract_name}.ts (${const_name}, ${abi_length} entries)"
  (( EXPORTED++ )) || true

done < <(find "$CONTRACTS_OUT" -name "*.json" -print0 2>/dev/null)

echo ""
echo "──────────────────────────────────────────────"
echo "  Exported: ${EXPORTED}   Skipped: ${SKIPPED}"
echo "──────────────────────────────────────────────"
echo ""

if [[ "$EXPORTED" -eq 0 ]]; then
  echo "ERROR: No ABI files exported. Did 'forge build' succeed?" >&2
  exit 1
fi

echo "  Import example:"
echo "  import { MY_CONTRACT_ABI } from '@/abis/MyContract'"
echo ""
